### ISSUE TITLE
Update test dependencies to support JDKs >8

### ISSUE THREAD

**Issue by SCdF** [medic/cht-gateway#151]
Currently to dev locally you need to run JDK8, otherwise running `make test` will fail with a reflection error that occurs in a test library that we use on JDKs greater than 8.

It's a pain to run 8, as it's a very old version and there aren't any particularly good ways of running multiple Java versions side by side (at least not on linux).

We should update this library, or replace it, so we can use JDK11 etc

**Comment by mrsarm** [comment]
Closing this in favor of https://github.com/medic/cht-gateway/issues/178 that has a broader scope.
