### ISSUE TITLE
Upgrade CI to use Github Actions

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-gateway#174]
Travis seems to be winding down the free tier with very long queue times, so we're migrating the repositories to use Github Actions.

Please replace Travis with Github Actions.

**Comment by m5r** [comment]
This has been merged with https://github.com/medic/cht-gateway/issues/178 and is ready for AT on branch `178-upgrade-build`  
[PR link](https://github.com/medic/cht-gateway/pull/183)  
[Initial PR link](https://github.com/medic/cht-gateway/pull/184)

**Comment by ngaruko** [comment]
1. App still load
2. ci actions pass on Github
![image](https://user-images.githubusercontent.com/6979995/148150233-9205eafb-283c-4b8d-ad4b-58cf74603fbb.png)

3. Release APKs generated if tagged
![image](https://user-images.githubusercontent.com/6979995/148160321-ca22d5db-263a-4ce3-87cd-51fd20c87e8c.png)
 
Good to merge @m5r
